# Generated by Django 4.1.6 on 2023-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('type_of_teach', models.CharField(blank=True, choices=[('privat', 'Лично, частным образом'), ('professional', 'Лично, профессионально'), ('online', 'Онлайн'), ('other', 'Другое')], max_length=100, null=True)),
                ('experience', models.CharField(blank=True, choices=[('1+', 'Больше одного года'), ('5+', 'Больше пяти лет'), ('10+', 'Больше десяти лет')], max_length=100, null=True)),
                ('audience', models.CharField(blank=True, choices=[('no aud', 'В настоящее время нет'), ('small aud', 'У меня маленькая аудитория'), ('normal aud', 'У меня достаточная аудитория')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('activation_code', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
